# Generated by Django 4.2.1 on 2023-05-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.genre'),
        ),
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album'),
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(to='app.album'),
        ),
    ]
